#!usr/bin/perl/ -w
use strict;
use warnings;

use Bio::AlignIO;
use Bio::LocatableSeq;

my @files=glob '*_nogap.fa';
foreach my $fls(@files){
        my $align_file = $fls;
        my $out_file = '';
        $out_file=$fls . '_table.txt';


	my $str = Bio::AlignIO->new('-file' => $align_file);
	my $aln = $str->next_aln();

	my $seq1 = $aln->get_seq_by_pos(1);
	my $seq2 = $aln->get_seq_by_pos(2);
	my $seq3 = $aln->get_seq_by_pos(3);
	my $seq4 = $aln->get_seq_by_pos(4);
	my $seq5 = $aln->get_seq_by_pos(5);
	my $seq6 = $aln->get_seq_by_pos(6);
	my $seq7 = $aln->get_seq_by_pos(7);
	my $seq8 = $aln->get_seq_by_pos(8);
	my $seq9 = $aln->get_seq_by_pos(9);
	my $seq10 = $aln->get_seq_by_pos(10);
	my $seq11 = $aln->get_seq_by_pos(11);
	my $seq12 = $aln->get_seq_by_pos(12);
	my $seq13 = $aln->get_seq_by_pos(13);
	my $seq14 = $aln->get_seq_by_pos(14);
	my $seq15 = $aln->get_seq_by_pos(15);
	my $seq16 = $aln->get_seq_by_pos(16);
	my $seq17 = $aln->get_seq_by_pos(17);
	my $seq18 = $aln->get_seq_by_pos(18);
	my $seq19 = $aln->get_seq_by_pos(19);
	my $seq20 = $aln->get_seq_by_pos(20);
	my $seq21 = $aln->get_seq_by_pos(21);
	my $seq22 = $aln->get_seq_by_pos(22);
	my $seq23 = $aln->get_seq_by_pos(23);
	my $seq24 = $aln->get_seq_by_pos(24);
	my $seq25 = $aln->get_seq_by_pos(25);
	my $seq26 = $aln->get_seq_by_pos(26);
	my $seq27 = $aln->get_seq_by_pos(27);
	my $seq28 = $aln->get_seq_by_pos(28);
	my $seq29 = $aln->get_seq_by_pos(29);
	my $seq30 = $aln->get_seq_by_pos(30);
	my $seq31 = $aln->get_seq_by_pos(31);
	my $seq32 = $aln->get_seq_by_pos(32);
	my $seq33 = $aln->get_seq_by_pos(33);
	my $seq34 = $aln->get_seq_by_pos(34);
	my $seq35 = $aln->get_seq_by_pos(35);
	my $seq36 = $aln->get_seq_by_pos(36);
	my $seq37 = $aln->get_seq_by_pos(37);
	my $seq38 = $aln->get_seq_by_pos(38);
	my $seq39 = $aln->get_seq_by_pos(39);
	my $seq40 = $aln->get_seq_by_pos(40);
	my $seq41 = $aln->get_seq_by_pos(41);
	my $seq42 = $aln->get_seq_by_pos(42);
	my $seq43 = $aln->get_seq_by_pos(43);
	my $seq44 = $aln->get_seq_by_pos(44);
	my $seq45 = $aln->get_seq_by_pos(45);
	my $seq46 = $aln->get_seq_by_pos(46);
	my $seq47 = $aln->get_seq_by_pos(47);
	my $seq48 = $aln->get_seq_by_pos(48);
	my $seq49 = $aln->get_seq_by_pos(49);
	my $seq50 = $aln->get_seq_by_pos(50);
	my $seq51 = $aln->get_seq_by_pos(51);
	my $seq52 = $aln->get_seq_by_pos(52);
	my $seq53 = $aln->get_seq_by_pos(53);
	my $seq54 = $aln->get_seq_by_pos(54);
	my $seq55 = $aln->get_seq_by_pos(55);
	my $seq56 = $aln->get_seq_by_pos(56);
	my $seq57 = $aln->get_seq_by_pos(57);
	my $seq58 = $aln->get_seq_by_pos(58);
	my $seq59 = $aln->get_seq_by_pos(59);
	my $seq60 = $aln->get_seq_by_pos(60);
	my $seq61 = $aln->get_seq_by_pos(61);
	my $seq62 = $aln->get_seq_by_pos(62);
	my $seq63 = $aln->get_seq_by_pos(63);
	my $seq64 = $aln->get_seq_by_pos(64);
	my $seq65 = $aln->get_seq_by_pos(65);
	my $seq66 = $aln->get_seq_by_pos(66);
	my $seq67 = $aln->get_seq_by_pos(67);
	my $seq68 = $aln->get_seq_by_pos(68);
	my $seq69 = $aln->get_seq_by_pos(69);
	my $seq70 = $aln->get_seq_by_pos(70);
	my $seq71 = $aln->get_seq_by_pos(71);
	my $seq72 = $aln->get_seq_by_pos(72);
	my $seq73 = $aln->get_seq_by_pos(73);
	my $seq74 = $aln->get_seq_by_pos(74);
	my $seq75 = $aln->get_seq_by_pos(75);
	my $seq76 = $aln->get_seq_by_pos(76);
	my $seq77 = $aln->get_seq_by_pos(77);
	my $seq78 = $aln->get_seq_by_pos(78);
	my $seq79 = $aln->get_seq_by_pos(79);
	my $seq80 = $aln->get_seq_by_pos(80);
	my $seq81 = $aln->get_seq_by_pos(81);
	my $seq82 = $aln->get_seq_by_pos(82);
	my $seq83 = $aln->get_seq_by_pos(83);
	my $seq84 = $aln->get_seq_by_pos(84);
	my $seq85 = $aln->get_seq_by_pos(85);
	my $seq86 = $aln->get_seq_by_pos(86);
	my $seq87 = $aln->get_seq_by_pos(87);
	my $seq88 = $aln->get_seq_by_pos(88);
	my $seq89 = $aln->get_seq_by_pos(89);
	my $seq90 = $aln->get_seq_by_pos(90);
	my $seq91 = $aln->get_seq_by_pos(91);
	my $seq92 = $aln->get_seq_by_pos(92);
	my $seq93 = $aln->get_seq_by_pos(93);
	my $seq94 = $aln->get_seq_by_pos(94);
	my $seq95 = $aln->get_seq_by_pos(95);
	my $seq96 = $aln->get_seq_by_pos(96);
	my $seq97 = $aln->get_seq_by_pos(97);
	my $seq98 = $aln->get_seq_by_pos(98);
	my $seq99 = $aln->get_seq_by_pos(99);
	my $seq100 = $aln->get_seq_by_pos(100);
	my $seq101 = $aln->get_seq_by_pos(101);
	my $seq102 = $aln->get_seq_by_pos(102);
	my $seq103 = $aln->get_seq_by_pos(103);
	my $seq104 = $aln->get_seq_by_pos(104);
	my $seq105 = $aln->get_seq_by_pos(105);
	my $seq106 = $aln->get_seq_by_pos(106);
	my $seq107 = $aln->get_seq_by_pos(107);
	my $seq108 = $aln->get_seq_by_pos(108);
	my $seq109 = $aln->get_seq_by_pos(109);
	my $seq110 = $aln->get_seq_by_pos(110);
	my $seq111 = $aln->get_seq_by_pos(111);
	my $seq112 = $aln->get_seq_by_pos(112);
	my $seq113 = $aln->get_seq_by_pos(113);
	my $seq114 = $aln->get_seq_by_pos(114);
	my $seq115 = $aln->get_seq_by_pos(115);
	my $seq116 = $aln->get_seq_by_pos(116);
	my $seq117 = $aln->get_seq_by_pos(117);
	my $seq118 = $aln->get_seq_by_pos(118);
	my $seq119 = $aln->get_seq_by_pos(119);
	my $seq120 = $aln->get_seq_by_pos(120);
	my $seq121 = $aln->get_seq_by_pos(121);
	my $seq122 = $aln->get_seq_by_pos(122);
	my $seq123 = $aln->get_seq_by_pos(123);
	my $seq124 = $aln->get_seq_by_pos(124);
	my $seq125 = $aln->get_seq_by_pos(125);
	my $seq126 = $aln->get_seq_by_pos(126);
	my $seq127 = $aln->get_seq_by_pos(127);
	my $seq128 = $aln->get_seq_by_pos(128);
	my $seq129 = $aln->get_seq_by_pos(129);
	my $seq130 = $aln->get_seq_by_pos(130);
	my $seq131 = $aln->get_seq_by_pos(131);
	my $seq132 = $aln->get_seq_by_pos(132);
	my $seq133 = $aln->get_seq_by_pos(133);
	my $seq134 = $aln->get_seq_by_pos(134);
	my $seq135 = $aln->get_seq_by_pos(135);
	my $seq136 = $aln->get_seq_by_pos(136);
	my $seq137 = $aln->get_seq_by_pos(137);
	my $seq138 = $aln->get_seq_by_pos(138);
	my $seq139 = $aln->get_seq_by_pos(139);
	my $seq140 = $aln->get_seq_by_pos(140);
	my $seq141 = $aln->get_seq_by_pos(141);
	my $seq142 = $aln->get_seq_by_pos(142);
	my $seq143 = $aln->get_seq_by_pos(143);
	my $seq144 = $aln->get_seq_by_pos(144);
	my $seq145 = $aln->get_seq_by_pos(145);
	my $seq146 = $aln->get_seq_by_pos(146);
	my $seq147 = $aln->get_seq_by_pos(147);
	my $seq148 = $aln->get_seq_by_pos(148);
	my $seq149 = $aln->get_seq_by_pos(149);
	my $seq150 = $aln->get_seq_by_pos(150);
	my $seq151 = $aln->get_seq_by_pos(151);
	my $seq152 = $aln->get_seq_by_pos(152);
	my $seq153 = $aln->get_seq_by_pos(153);
	my $seq154 = $aln->get_seq_by_pos(154);
	my $seq155 = $aln->get_seq_by_pos(155);
	my $seq156 = $aln->get_seq_by_pos(156);
	my $seq157 = $aln->get_seq_by_pos(157);
	my $seq158 = $aln->get_seq_by_pos(158);
	my $seq159 = $aln->get_seq_by_pos(159);
	my $seq160 = $aln->get_seq_by_pos(160);
	my $seq161 = $aln->get_seq_by_pos(161);
	my $seq162 = $aln->get_seq_by_pos(162);
	my $seq163 = $aln->get_seq_by_pos(163);
	my $seq164 = $aln->get_seq_by_pos(164);
	my $seq165 = $aln->get_seq_by_pos(165);
	my $seq166 = $aln->get_seq_by_pos(166);
	my $seq167 = $aln->get_seq_by_pos(167);
	my $seq168 = $aln->get_seq_by_pos(168);
	my $seq169 = $aln->get_seq_by_pos(169);
	my $seq170 = $aln->get_seq_by_pos(170);
	my $seq171 = $aln->get_seq_by_pos(171);
	my $seq172 = $aln->get_seq_by_pos(172);
	my $seq173 = $aln->get_seq_by_pos(173);
	my $seq174 = $aln->get_seq_by_pos(174);
	my $seq175 = $aln->get_seq_by_pos(175);
	my $seq176 = $aln->get_seq_by_pos(176);
	my $seq177 = $aln->get_seq_by_pos(177);
	my $seq178 = $aln->get_seq_by_pos(178);
	my $seq179 = $aln->get_seq_by_pos(179);
	my $seq180 = $aln->get_seq_by_pos(180);
	my $seq181 = $aln->get_seq_by_pos(181);
	my $seq182 = $aln->get_seq_by_pos(182);
	my $seq183 = $aln->get_seq_by_pos(183);
	my $seq184 = $aln->get_seq_by_pos(184);
	my $seq185 = $aln->get_seq_by_pos(185);
	my $seq186 = $aln->get_seq_by_pos(186);
	my $seq187 = $aln->get_seq_by_pos(187);
	my $seq188 = $aln->get_seq_by_pos(188);
	my $seq189 = $aln->get_seq_by_pos(189);
	my $seq190 = $aln->get_seq_by_pos(190);
	my $seq191 = $aln->get_seq_by_pos(191);
	my $seq192 = $aln->get_seq_by_pos(192);
	my $seq193 = $aln->get_seq_by_pos(193);
	my $seq194 = $aln->get_seq_by_pos(194);
	my $seq195 = $aln->get_seq_by_pos(195);
	my $seq196 = $aln->get_seq_by_pos(196);
	my $seq197 = $aln->get_seq_by_pos(197);


	open(OUTPUT, ">$out_file") or die "error";

	for (my $col = 1; $col<=$aln->length; $col++) 
	{
    		my $char_seq1 = $seq1->subseq($col, $col);
    		my $char_seq2 = $seq2->subseq($col, $col);
    		my $char_seq3 = $seq3->subseq($col, $col);
    		my $char_seq4 = $seq4->subseq($col, $col);
    		my $char_seq5 = $seq5->subseq($col, $col);
    		my $char_seq6 = $seq6->subseq($col, $col);
    		my $char_seq7 = $seq7->subseq($col, $col);
    		my $char_seq8 = $seq8->subseq($col, $col);
    		my $char_seq9 = $seq9->subseq($col, $col);
    		my $char_seq10 = $seq10->subseq($col, $col);
    		my $char_seq11 = $seq11->subseq($col, $col);
    		my $char_seq12 = $seq12->subseq($col, $col);
    		my $char_seq13 = $seq13->subseq($col, $col);
    		my $char_seq14 = $seq14->subseq($col, $col);
    		my $char_seq15 = $seq15->subseq($col, $col);
   	 	my $char_seq16 = $seq16->subseq($col, $col);
    		my $char_seq17 = $seq17->subseq($col, $col);
    		my $char_seq18 = $seq18->subseq($col, $col);
    		my $char_seq19 = $seq19->subseq($col, $col);
    		my $char_seq20 = $seq20->subseq($col, $col);
    		my $char_seq21 = $seq21->subseq($col, $col);
    		my $char_seq22 = $seq22->subseq($col, $col);
    		my $char_seq23 = $seq23->subseq($col, $col);
    		my $char_seq24 = $seq24->subseq($col, $col);
    		my $char_seq25 = $seq25->subseq($col, $col);
    		my $char_seq26 = $seq26->subseq($col, $col);
    		my $char_seq27 = $seq27->subseq($col, $col);
    		my $char_seq28 = $seq28->subseq($col, $col);
    		my $char_seq29 = $seq29->subseq($col, $col);
    		my $char_seq30 = $seq30->subseq($col, $col);
    		my $char_seq31 = $seq31->subseq($col, $col);
    		my $char_seq32 = $seq32->subseq($col, $col);
    		my $char_seq33 = $seq33->subseq($col, $col);
    		my $char_seq34 = $seq34->subseq($col, $col);
    		my $char_seq35 = $seq35->subseq($col, $col);
    		my $char_seq36 = $seq36->subseq($col, $col);
    		my $char_seq37 = $seq37->subseq($col, $col);
   		my $char_seq38 = $seq38->subseq($col, $col);
    		my $char_seq39 = $seq39->subseq($col, $col);
    		my $char_seq40 = $seq40->subseq($col, $col);
    		my $char_seq41 = $seq41->subseq($col, $col);
    		my $char_seq42 = $seq42->subseq($col, $col);
    		my $char_seq43 = $seq43->subseq($col, $col);
    		my $char_seq44 = $seq44->subseq($col, $col);
    		my $char_seq45 = $seq45->subseq($col, $col);
    		my $char_seq46 = $seq46->subseq($col, $col);
    		my $char_seq47 = $seq47->subseq($col, $col);
    		my $char_seq48 = $seq48->subseq($col, $col);
    		my $char_seq49 = $seq49->subseq($col, $col);
    		my $char_seq50 = $seq50->subseq($col, $col);
    		my $char_seq51 = $seq51->subseq($col, $col);
    		my $char_seq52 = $seq52->subseq($col, $col);
    		my $char_seq53 = $seq53->subseq($col, $col);
    		my $char_seq54 = $seq54->subseq($col, $col);
    		my $char_seq55 = $seq55->subseq($col, $col);
    		my $char_seq56 = $seq56->subseq($col, $col);
   		my $char_seq57 = $seq57->subseq($col, $col);
    		my $char_seq58 = $seq58->subseq($col, $col);
    		my $char_seq59 = $seq59->subseq($col, $col);
    		my $char_seq60 = $seq60->subseq($col, $col);
    		my $char_seq61 = $seq61->subseq($col, $col);
    		my $char_seq62 = $seq62->subseq($col, $col);
   		my $char_seq63 = $seq63->subseq($col, $col);
    		my $char_seq64 = $seq64->subseq($col, $col);
    		my $char_seq65 = $seq65->subseq($col, $col);
    		my $char_seq66 = $seq66->subseq($col, $col);
    		my $char_seq67 = $seq67->subseq($col, $col);
    		my $char_seq68 = $seq68->subseq($col, $col);
    		my $char_seq69 = $seq69->subseq($col, $col);
    		my $char_seq70 = $seq70->subseq($col, $col);
    		my $char_seq71 = $seq71->subseq($col, $col);
    		my $char_seq72 = $seq72->subseq($col, $col);
    		my $char_seq73 = $seq73->subseq($col, $col);
    		my $char_seq74 = $seq74->subseq($col, $col);
    		my $char_seq75 = $seq75->subseq($col, $col);
    		my $char_seq76 = $seq76->subseq($col, $col);
    		my $char_seq77 = $seq77->subseq($col, $col);
    		my $char_seq78 = $seq78->subseq($col, $col);
    		my $char_seq79 = $seq79->subseq($col, $col);
    		my $char_seq80 = $seq80->subseq($col, $col);
    		my $char_seq81 = $seq81->subseq($col, $col);
    		my $char_seq82 = $seq82->subseq($col, $col);
    		my $char_seq83 = $seq83->subseq($col, $col);
    		my $char_seq84 = $seq84->subseq($col, $col);
    		my $char_seq85 = $seq85->subseq($col, $col);
    		my $char_seq86 = $seq86->subseq($col, $col);
    		my $char_seq87 = $seq87->subseq($col, $col);
    		my $char_seq88 = $seq88->subseq($col, $col);
    		my $char_seq89 = $seq89->subseq($col, $col);
    		my $char_seq90 = $seq90->subseq($col, $col);
    		my $char_seq91 = $seq91->subseq($col, $col);
    		my $char_seq92 = $seq92->subseq($col, $col);
    		my $char_seq93 = $seq93->subseq($col, $col);
    		my $char_seq94 = $seq94->subseq($col, $col);
    		my $char_seq95 = $seq95->subseq($col, $col);
    		my $char_seq96 = $seq96->subseq($col, $col);
    		my $char_seq97 = $seq97->subseq($col, $col);
    		my $char_seq98 = $seq98->subseq($col, $col);
    		my $char_seq99 = $seq99->subseq($col, $col);
    		my $char_seq100 = $seq100->subseq($col, $col);
   		my $char_seq101 = $seq101->subseq($col, $col);
    		my $char_seq102 = $seq102->subseq($col, $col);
   		my $char_seq103 = $seq103->subseq($col, $col);
    		my $char_seq104 = $seq104->subseq($col, $col);
    		my $char_seq105 = $seq105->subseq($col, $col);
    		my $char_seq106 = $seq106->subseq($col, $col);
    		my $char_seq107 = $seq107->subseq($col, $col);
    		my $char_seq108 = $seq108->subseq($col, $col);
    		my $char_seq109 = $seq109->subseq($col, $col);
    		my $char_seq110 = $seq110->subseq($col, $col);
    		my $char_seq111 = $seq111->subseq($col, $col);
    		my $char_seq112 = $seq112->subseq($col, $col);
    		my $char_seq113 = $seq113->subseq($col, $col);
    		my $char_seq114 = $seq114->subseq($col, $col);
    		my $char_seq115 = $seq115->subseq($col, $col);
    		my $char_seq116 = $seq116->subseq($col, $col);
    		my $char_seq117 = $seq117->subseq($col, $col);
    		my $char_seq118 = $seq118->subseq($col, $col);
    		my $char_seq119 = $seq119->subseq($col, $col);
    		my $char_seq120 = $seq120->subseq($col, $col);
    		my $char_seq121 = $seq121->subseq($col, $col);
    		my $char_seq122 = $seq122->subseq($col, $col);
    		my $char_seq123 = $seq123->subseq($col, $col);
    		my $char_seq124 = $seq124->subseq($col, $col);
    		my $char_seq125 = $seq125->subseq($col, $col);
    		my $char_seq126 = $seq126->subseq($col, $col);
   		my $char_seq127 = $seq127->subseq($col, $col);
   		my $char_seq128 = $seq128->subseq($col, $col);
   		my $char_seq129 = $seq129->subseq($col, $col);
    		my $char_seq130 = $seq130->subseq($col, $col);
    		my $char_seq131 = $seq131->subseq($col, $col);
    		my $char_seq132 = $seq132->subseq($col, $col);
    		my $char_seq133 = $seq133->subseq($col, $col);
    		my $char_seq134 = $seq134->subseq($col, $col);
    		my $char_seq135 = $seq135->subseq($col, $col);
   		my $char_seq136 = $seq136->subseq($col, $col);
    		my $char_seq137 = $seq137->subseq($col, $col);
   		my $char_seq138 = $seq138->subseq($col, $col);
    		my $char_seq139 = $seq139->subseq($col, $col);
    		my $char_seq140 = $seq140->subseq($col, $col);
    		my $char_seq141 = $seq141->subseq($col, $col);
    		my $char_seq142 = $seq142->subseq($col, $col);
    		my $char_seq143 = $seq143->subseq($col, $col);
    		my $char_seq144 = $seq144->subseq($col, $col);
   		my $char_seq145 = $seq145->subseq($col, $col);
    		my $char_seq146 = $seq146->subseq($col, $col);
   		my $char_seq147 = $seq147->subseq($col, $col);
    		my $char_seq148 = $seq148->subseq($col, $col);
    		my $char_seq149 = $seq149->subseq($col, $col);
    		my $char_seq150 = $seq150->subseq($col, $col);
    		my $char_seq151 = $seq151->subseq($col, $col);
    		my $char_seq152 = $seq152->subseq($col, $col);
    		my $char_seq153 = $seq153->subseq($col, $col);
    		my $char_seq154 = $seq154->subseq($col, $col);
    		my $char_seq155 = $seq155->subseq($col, $col);
    		my $char_seq156 = $seq156->subseq($col, $col);
    		my $char_seq157 = $seq157->subseq($col, $col);
   		my $char_seq158 = $seq158->subseq($col, $col);
    		my $char_seq159 = $seq159->subseq($col, $col);
    		my $char_seq160 = $seq160->subseq($col, $col);
    		my $char_seq161 = $seq161->subseq($col, $col);
   		my $char_seq162 = $seq162->subseq($col, $col);
    		my $char_seq163 = $seq163->subseq($col, $col);
    		my $char_seq164 = $seq164->subseq($col, $col);
    		my $char_seq165 = $seq165->subseq($col, $col);
    		my $char_seq166 = $seq166->subseq($col, $col);
    		my $char_seq167 = $seq167->subseq($col, $col);
    		my $char_seq168 = $seq168->subseq($col, $col);
    		my $char_seq169 = $seq169->subseq($col, $col);
    		my $char_seq170 = $seq170->subseq($col, $col);
    		my $char_seq171 = $seq171->subseq($col, $col);
    		my $char_seq172 = $seq172->subseq($col, $col);
    		my $char_seq173 = $seq173->subseq($col, $col);
    		my $char_seq174 = $seq174->subseq($col, $col);
    		my $char_seq175 = $seq175->subseq($col, $col);
    		my $char_seq176 = $seq176->subseq($col, $col);
    		my $char_seq177 = $seq177->subseq($col, $col);
   		my $char_seq178 = $seq178->subseq($col, $col);
    		my $char_seq179 = $seq179->subseq($col, $col);
    		my $char_seq180 = $seq180->subseq($col, $col);
    		my $char_seq181 = $seq181->subseq($col, $col);
    		my $char_seq182 = $seq182->subseq($col, $col);
    		my $char_seq183 = $seq183->subseq($col, $col);
    		my $char_seq184 = $seq184->subseq($col, $col);
    		my $char_seq185 = $seq185->subseq($col, $col);
   		my $char_seq186 = $seq186->subseq($col, $col);
    		my $char_seq187 = $seq187->subseq($col, $col);
    		my $char_seq188 = $seq188->subseq($col, $col);
    		my $char_seq189 = $seq189->subseq($col, $col);
    		my $char_seq190 = $seq190->subseq($col, $col);
    		my $char_seq191 = $seq191->subseq($col, $col);
    		my $char_seq192 = $seq192->subseq($col, $col);
    		my $char_seq193 = $seq193->subseq($col, $col);
    		my $char_seq194 = $seq194->subseq($col, $col);
    		my $char_seq195 = $seq195->subseq($col, $col);
   		my $char_seq196 = $seq196->subseq($col, $col);
   		my $char_seq197 = $seq197->subseq($col, $col);


    		print OUTPUT $char_seq1, "\t";
   		print OUTPUT $char_seq2, "\t";
    		print OUTPUT $char_seq3, "\t";
    		print OUTPUT $char_seq4, "\t";
    		print OUTPUT $char_seq5, "\t";
    		print OUTPUT $char_seq6, "\t";
    		print OUTPUT $char_seq7, "\t";
   		print OUTPUT $char_seq8, "\t";
    		print OUTPUT $char_seq9, "\t";
    		print OUTPUT $char_seq10, "\t";
    		print OUTPUT $char_seq11, "\t";
    		print OUTPUT $char_seq12, "\t";
    		print OUTPUT $char_seq13, "\t";
    		print OUTPUT $char_seq14, "\t";
    		print OUTPUT $char_seq15, "\t";
   		print OUTPUT $char_seq16, "\t";
    		print OUTPUT $char_seq17, "\t";
    		print OUTPUT $char_seq18, "\t";
    		print OUTPUT $char_seq19, "\t";
    		print OUTPUT $char_seq20, "\t";
   		print OUTPUT $char_seq21, "\t";
   		print OUTPUT $char_seq22, "\t";
   		print OUTPUT $char_seq23, "\t";
    		print OUTPUT $char_seq24, "\t";
    		print OUTPUT $char_seq25, "\t";
    		print OUTPUT $char_seq26, "\t";
    		print OUTPUT $char_seq27, "\t";
   		print OUTPUT $char_seq28, "\t";
    		print OUTPUT $char_seq29, "\t";
    		print OUTPUT $char_seq30, "\t";
    		print OUTPUT $char_seq31, "\t";
    		print OUTPUT $char_seq32, "\t";
    		print OUTPUT $char_seq33, "\t";
    		print OUTPUT $char_seq34, "\t";
    		print OUTPUT $char_seq35, "\t";
    		print OUTPUT $char_seq36, "\t";
    		print OUTPUT $char_seq37, "\t";
    		print OUTPUT $char_seq38, "\t";
    		print OUTPUT $char_seq39, "\t";
    		print OUTPUT $char_seq40, "\t";
    		print OUTPUT $char_seq41, "\t";
    		print OUTPUT $char_seq42, "\t";
    		print OUTPUT $char_seq43, "\t";
    		print OUTPUT $char_seq44, "\t";
    		print OUTPUT $char_seq45, "\t";
    		print OUTPUT $char_seq46, "\t";
  		print OUTPUT $char_seq47, "\t";
    		print OUTPUT $char_seq48, "\t";
    		print OUTPUT $char_seq49, "\t";
   		print OUTPUT $char_seq50, "\t";
    		print OUTPUT $char_seq51, "\t";
    		print OUTPUT $char_seq52, "\t";
    		print OUTPUT $char_seq53, "\t";
    		print OUTPUT $char_seq54, "\t";
    		print OUTPUT $char_seq55, "\t";
    		print OUTPUT $char_seq56, "\t";
    		print OUTPUT $char_seq57, "\t";
    		print OUTPUT $char_seq58, "\t";
    		print OUTPUT $char_seq59, "\t";
    		print OUTPUT $char_seq60, "\t";
    		print OUTPUT $char_seq61, "\t";
    		print OUTPUT $char_seq62, "\t";
    		print OUTPUT $char_seq63, "\t";
    		print OUTPUT $char_seq64, "\t";
    		print OUTPUT $char_seq65, "\t";
    		print OUTPUT $char_seq66, "\t";
    		print OUTPUT $char_seq67, "\t";
    		print OUTPUT $char_seq68, "\t";
    		print OUTPUT $char_seq69, "\t";
    		print OUTPUT $char_seq70, "\t";
    		print OUTPUT $char_seq71, "\t";
   		print OUTPUT $char_seq72, "\t";
    		print OUTPUT $char_seq73, "\t";
    		print OUTPUT $char_seq74, "\t";
    		print OUTPUT $char_seq75, "\t";
   		print OUTPUT $char_seq76, "\t";
    		print OUTPUT $char_seq77, "\t";
    		print OUTPUT $char_seq78, "\t";
    		print OUTPUT $char_seq79, "\t";
    		print OUTPUT $char_seq80, "\t";
    		print OUTPUT $char_seq81, "\t";
    		print OUTPUT $char_seq82, "\t";
    		print OUTPUT $char_seq83, "\t";
    		print OUTPUT $char_seq84, "\t";
    		print OUTPUT $char_seq85, "\t";
    		print OUTPUT $char_seq86, "\t";
    		print OUTPUT $char_seq87, "\t";
    		print OUTPUT $char_seq88, "\t";
    		print OUTPUT $char_seq89, "\t";
    		print OUTPUT $char_seq90, "\t";
    		print OUTPUT $char_seq91, "\t";
   		print OUTPUT $char_seq92, "\t";
    		print OUTPUT $char_seq93, "\t";
    		print OUTPUT $char_seq94, "\t";
   		print OUTPUT $char_seq95, "\t";
    		print OUTPUT $char_seq96, "\t";
    		print OUTPUT $char_seq97, "\t";
    		print OUTPUT $char_seq98, "\t";
    		print OUTPUT $char_seq99, "\t";
    		print OUTPUT $char_seq100, "\t";
    		print OUTPUT $char_seq101, "\t";
    		print OUTPUT $char_seq102, "\t";
    		print OUTPUT $char_seq103, "\t";
    		print OUTPUT $char_seq104, "\t";
    		print OUTPUT $char_seq105, "\t";
    		print OUTPUT $char_seq106, "\t";
    		print OUTPUT $char_seq107, "\t";
    		print OUTPUT $char_seq108, "\t";
    		print OUTPUT $char_seq109, "\t";
    		print OUTPUT $char_seq110, "\t";
    		print OUTPUT $char_seq111, "\t";
    		print OUTPUT $char_seq112, "\t";
    		print OUTPUT $char_seq113, "\t";
    		print OUTPUT $char_seq114, "\t";
    		print OUTPUT $char_seq115, "\t";
    		print OUTPUT $char_seq116, "\t";
    		print OUTPUT $char_seq117, "\t";
    		print OUTPUT $char_seq118, "\t";
    		print OUTPUT $char_seq119, "\t";
    		print OUTPUT $char_seq120, "\t";
    		print OUTPUT $char_seq121, "\t";
    		print OUTPUT $char_seq122, "\t";
    		print OUTPUT $char_seq123, "\t";
    		print OUTPUT $char_seq124, "\t";
    		print OUTPUT $char_seq125, "\t";
   		print OUTPUT $char_seq126, "\t";
   		print OUTPUT $char_seq127, "\t";
    		print OUTPUT $char_seq128, "\t";
    		print OUTPUT $char_seq129, "\t";
    		print OUTPUT $char_seq130, "\t";
    		print OUTPUT $char_seq131, "\t";
    		print OUTPUT $char_seq132, "\t";
    		print OUTPUT $char_seq133, "\t";
    		print OUTPUT $char_seq134, "\t";
    		print OUTPUT $char_seq135, "\t";
    		print OUTPUT $char_seq136, "\t";
    		print OUTPUT $char_seq137, "\t";
    		print OUTPUT $char_seq138, "\t";
    		print OUTPUT $char_seq139, "\t";
    		print OUTPUT $char_seq140, "\t";
    		print OUTPUT $char_seq141, "\t";
    		print OUTPUT $char_seq142, "\t";
    		print OUTPUT $char_seq143, "\t";
    		print OUTPUT $char_seq144, "\t";
    		print OUTPUT $char_seq145, "\t";
    		print OUTPUT $char_seq146, "\t";
    		print OUTPUT $char_seq147, "\t";
    		print OUTPUT $char_seq148, "\t";
    		print OUTPUT $char_seq149, "\t";
    		print OUTPUT $char_seq150, "\t";
    		print OUTPUT $char_seq151, "\t";
    		print OUTPUT $char_seq152, "\t";
    		print OUTPUT $char_seq153, "\t";
    		print OUTPUT $char_seq154, "\t";
    		print OUTPUT $char_seq155, "\t";
    		print OUTPUT $char_seq156, "\t";
    		print OUTPUT $char_seq157, "\t";
    		print OUTPUT $char_seq158, "\t";
    		print OUTPUT $char_seq159, "\t";
    		print OUTPUT $char_seq160, "\t";
    		print OUTPUT $char_seq161, "\t";
    		print OUTPUT $char_seq162, "\t";
    		print OUTPUT $char_seq163, "\t";
    		print OUTPUT $char_seq164, "\t";
    		print OUTPUT $char_seq165, "\t";
    		print OUTPUT $char_seq166, "\t";
    		print OUTPUT $char_seq167, "\t";
    		print OUTPUT $char_seq168, "\t";
    		print OUTPUT $char_seq169, "\t";
    		print OUTPUT $char_seq170, "\t";
    		print OUTPUT $char_seq171, "\t";
    		print OUTPUT $char_seq172, "\t";
   		print OUTPUT $char_seq173, "\t";
    		print OUTPUT $char_seq174, "\t";
    		print OUTPUT $char_seq175, "\t";
    		print OUTPUT $char_seq176, "\t";
    		print OUTPUT $char_seq177, "\t";
   		print OUTPUT $char_seq178, "\t";
   		print OUTPUT $char_seq179, "\t";
    		print OUTPUT $char_seq180, "\t";
    		print OUTPUT $char_seq181, "\t";
    		print OUTPUT $char_seq182, "\t";
   		print OUTPUT $char_seq183, "\t";
    		print OUTPUT $char_seq184, "\t";
    		print OUTPUT $char_seq185, "\t";
    		print OUTPUT $char_seq186, "\t";
    		print OUTPUT $char_seq187, "\t";
    		print OUTPUT $char_seq188, "\t";
    		print OUTPUT $char_seq189, "\t";
    		print OUTPUT $char_seq190, "\t";
    		print OUTPUT $char_seq191, "\t";
    		print OUTPUT $char_seq192, "\t";
    		print OUTPUT $char_seq193, "\t";
    		print OUTPUT $char_seq194, "\t";
    		print OUTPUT $char_seq195, "\t";
    		print OUTPUT $char_seq196, "\t";
    		print OUTPUT $char_seq197, "\n";
	}

	close OUTPUT;
}
exit;
